"""add harvests_left

Revision ID: 47ab1743ac2a
Revises: 871f446c4069
Create Date: 2026-07-26 23:29:34.284658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ab1743ac2a'
down_revision: Union[str, Sequence[str], None] = '871f446c4069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garden_beds', sa.Column('harvests_left', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garden_beds', 'harvests_left')
    # ### end Alembic commands ###
