"""add plant_level to garden_bed

Revision ID: 8aee2d8f871b
Revises: e99eec036230
Create Date: 2026-08-20 00:03:15.976566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aee2d8f871b'
down_revision: Union[str, Sequence[str], None] = 'e99eec036230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garden_beds', sa.Column('plant_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garden_beds', 'plant_level')
    # ### end Alembic commands ###
