"""add harvest_item_id

Revision ID: eee3f8c082d3
Revises: 
Create Date: 2026-07-18 01:10:33.208467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee3f8c082d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('potency_boost', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('sell_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_seed', sa.String(), nullable=True),
    sa.Column('icon_sprout', sa.String(), nullable=True),
    sa.Column('icon_stem', sa.String(), nullable=True),
    sa.Column('icon_bud', sa.String(), nullable=True),
    sa.Column('icon_bloom', sa.String(), nullable=True),
    sa.Column('icon_mature', sa.String(), nullable=True),
    sa.Column('base_vitality', sa.Integer(), nullable=True),
    sa.Column('vitality_decay', sa.Integer(), nullable=True),
    sa.Column('essence_per_care', sa.Integer(), nullable=True),
    sa.Column('growth_per_care', sa.Integer(), nullable=True),
    sa.Column('min_harvest_stage', sa.Integer(), nullable=True),
    sa.Column('base_potency', sa.Integer(), nullable=True),
    sa.Column('harvest_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['harvest_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_plants_id'), 'plants', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('max_energy', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('days_in_game', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_nickname'), 'players', ['nickname'], unique=True)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=True)
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ingredient_1_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_2_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_3_id', sa.Integer(), nullable=True),
    sa.Column('result_item_id', sa.Integer(), nullable=False),
    sa.Column('result_quantity', sa.Integer(), nullable=True),
    sa.Column('base_success_chance', sa.Float(), nullable=True),
    sa.Column('quality_bonus_percent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_1_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['ingredient_2_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['ingredient_3_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['result_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_id'), 'recipes', ['id'], unique=False)
    op.create_table('garden_beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('vitality', sa.Integer(), nullable=True),
    sa.Column('essence', sa.Integer(), nullable=True),
    sa.Column('growth_stage', sa.Integer(), nullable=True),
    sa.Column('last_watered_at', sa.DateTime(), nullable=True),
    sa.Column('last_cleaned_at', sa.DateTime(), nullable=True),
    sa.Column('last_harvested_at', sa.DateTime(), nullable=True),
    sa.Column('last_moon_bath_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_until', sa.DateTime(), nullable=True),
    sa.Column('last_daily_update', sa.DateTime(), nullable=True),
    sa.Column('planted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garden_beds_id'), 'garden_beds', ['id'], unique=False)
    op.create_table('care_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_bed_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=False),
    sa.Column('effect', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['garden_bed_id'], ['garden_beds.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_logs_id'), 'care_logs', ['id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(), nullable=True),
    sa.Column('source_bed_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['source_bed_id'], ['garden_beds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_care_logs_id'), table_name='care_logs')
    op.drop_table('care_logs')
    op.drop_index(op.f('ix_garden_beds_id'), table_name='garden_beds')
    op.drop_table('garden_beds')
    op.drop_index(op.f('ix_recipes_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_nickname'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_plants_id'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
